export const EmployeeData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@webshop.com",
    department: "E-commerce",
    role: "Web Developer",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@webshop.com",
    department: "E-commerce",
    role: "Web Designer",
    photo: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@webshop.com",
    department: "E-commerce",
    role: "Project Manager",
    photo: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice.brown@webshop.com",
    department: "E-commerce",
    role: "Sales",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 5,
    name: "Mike Davis",
    email: "mike.davis@webshop.com",
    department: "E-commerce",
    role: "Marketing",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 6,
    name: "Jim Lee",
    email: "jim.lee@webshop.com",
    department: "E-commerce",
    role: "Accountant",
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 7,
    name: "Emma Taylor",
    email: "emma.taylor@webshop.com",
    department: "E-commerce",
    role: "Sales",
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 8,
    name: "David Kim",
    email: "david.kim@webshop.com",
    department: "E-commerce",
    role: "Software Engineer",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 9,
    name: "Emily Chen",
    email: "emily.chen@webshop.com",
    department: "E-commerce",
    role: "Designer",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 10,
    name: "Chris Lee",
    email: "chris.lee@webshop.com",
    department: "E-commerce",
    role: "Sales Manager",
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
  },
];
