export const EmployeeData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    department: "IT",
    role: "Software Engineer",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    department: "Sales",
    role: "Sales Representative",
    photo: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    department: "Marketing",
    role: "Content Writer",
    photo: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice.brown@example.com",
    department: "Human Resources",
    role: "Administrative Assistant",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 5,
    name: "Mike Jones",
    email: "mike.jones@example.com",
    department: "Finance",
    role: "Accountant",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 6,
    name: "Jim Lee",
    email: "jim.lee@example.com",
    department: "Legal",
    role: "Paralegal",
    photo: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 7,
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    department: "Sales",
    role: "Sales Representative",
    photo: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 8,
    name: "David Kim",
    email: "david.kim@example.com",
    department: "IT",
    role: "Software Engineer",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 9,
    name: "Emily Chen",
    email: "emily.chen@example.com",
    department: "Marketing",
    role: "Content Writer",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 10,
    name: "Chris Lee",
    email: "chris.lee@example.com",
    department: "Sales",
    role: "Sales Manager",
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
  },
];
