export const UserDummy = [
  {
    id: 1,
    type: "admin",
    avatar: "https://i.pravatar.cc/150?u=1",
    username: "Leonel_OReilly",
    firstName: "Dale",
    lastName: "Koelpin",
    phoneNumber: "1-512-123-9464",
    address: "0861 Wildner Terrace",
    city: "East Isadabel",
    country: "South Carolina",
    email: "Dale_Koelpin@rhyta.com",
    active: true,
  },
  {
    id: 2,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=2",
    username: "Jaylan.Lueilwitz66",
    firstName: "Margaretta",
    lastName: "Lakin",
    phoneNumber: "1-773-165-8540",
    address: "30998 Kacey Point",
    city: "New Eloy",
    country: "Kansas",
    email: "Margaretta.Lakin@yahoo.com",
    active: false,
  },
  {
    id: 3,
    type: "admin",
    avatar: "https://i.pravatar.cc/150?u=3",
    username: "Cindy9",
    firstName: "Margarete",
    lastName: "Hammes",
    phoneNumber: "1-134-784-6478",
    address: "87319 Emory Hill",
    city: "North Maribel",
    country: "Nebraska",
    email: "Margarete.Hammes@yahoo.com",
    active: true,
  },
  {
    id: 4,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=4",
    username: "Jaycee_Hermann",
    firstName: "Marianne",
    lastName: "Dietrich",
    phoneNumber: "1-632-121-7946",
    address: "54944 Schiller Terrace",
    city: "New Maribel",
    country: "Michigan",
    email: "Marianne_Dietrich@gmail.com",
    active: false,
  },
  {
    id: 5,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=5",
    username: "Darrell.Bosco",
    firstName: "Elody",
    lastName: "Schaden",
    phoneNumber: "1-407-787-1283",
    address: "15408 Lindgren Fork",
    city: "East Leola",
    country: "Florida",
    email: "Elody.Schaden@gmail.com",
    active: true,
  },
  {
    id: 6,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=6",
    username: "Carmelo_Hirthe",
    firstName: "Velma",
    lastName: "Muller",
    phoneNumber: "1-127-600-0075",
    address: "40808 Mertie Union",
    city: "New Rae",
    country: "Ohio",
    email: "Velma.Muller@gmail.com",
    active: false,
  },
  {
    id: 7,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=7",
    username: "Mozelle.Bartoletti",
    firstName: "Jazlyn",
    lastName: "Rodriguez",
    phoneNumber: "1-198-150-7840",
    address: "1606 Linda Village",
    city: "East Kaden",
    country: "Wisconsin",
    email: "Jazlyn.Rodriguez@yahoo.com",
    active: true,
  },
  {
    id: 8,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=8",
    username: "Kristofer.Bartoletti",
    firstName: "Rod",
    lastName: "Kuphal",
    phoneNumber: "1-788-122-6040",
    address: "59133 Avery Point",
    city: "South Estefania",
    country: "North Carolina",
    email: "Rod.Kuphal@gmail.com",
    active: false,
  },
  {
    id: 9,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=9",
    username: "Jessie.Kunde",
    firstName: "Leda",
    lastName: "Sawayn",
    phoneNumber: "1-186-632-6866",
    address: "10000 Jodie Harbor",
    city: "South Alexzander",
    country: "North Dakota",
    email: "Leda.Sawayn@yahoo.com",
    active: true,
  },
  {
    id: 10,
    type: "user",
    avatar: "https://i.pravatar.cc/150?u=10",
    username: "Margarita.Bosco",
    firstName: "Camila",
    lastName: "Maggio",
    phoneNumber: "1-164-805-0424",
    address: "09340 Kris Summit",
    city: "West Nathanael",
    country: "Iowa",
    email: "Camila.Maggio@gmail.com",
    active: false,
  },
];
